### ISSUE TITLE
guerrillamail defaults to different domain name

### ISSUE THREAD

**Issue by saeedesmaili** [vitorgalvao/temporary-email-workflow#2]
### Workflow version

2023.4

### Alfred version

5.1.4

### macOS version

13.5.1

### Debugger output

```alfred_debugger
-
```

### More details

I've set the email service to guerrillamail. When I use the workflow, an email address with `guerrillamail.com` gets added to my clipboard, but the opened browser tab is defaulted on another domain (most of the time it's `sharklasers.com`), so I never receive the email. Example:

What the workflow generated and added to my clipboard:
<img width="802" alt="image" src="https://github.com/vitorgalvao/temporary-email-workflow/assets/13351748/f6888b6e-f2d6-4015-a53e-41b1b1bf57c4">

What it should be and what the web page is waiting for an email for:
<img width="946" alt="image" src="https://github.com/vitorgalvao/temporary-email-workflow/assets/13351748/a2da9336-0055-42ae-8ad1-8122eb85d1d1">

I can change the domain to `guerrillamail.com` on the webpage manually before entering the email on the form I'm attempting to use, but I'd assume this is not how it should work. I understand that this is probably due to a change on guerrillamail.

**Comment by vitorgalvao** [comment]
Thank you for the detailed and understanding report. I can reproduce. I may be missing something but with a quick test I didn’t find a simple obvious fix to keep that domain, so I removed Guerrilla Mail in favour of Shark Lasers since that’ll effectively be the same.

If anyone has a solution which works to force the domain, I’m open to adding it to the workflow.

Just released `2024.1` with the change.
